//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecm.Service {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ecm.Service.Properties.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add action log failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string AddActionLogFail {
            get {
                return ResourceManager.GetString("AddActionLogFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add document type history failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string AddDocTypeHistory {
            get {
                return ResourceManager.GetString("AddDocTypeHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add document history failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string AddDocumentHistory {
            get {
                return ResourceManager.GetString("AddDocumentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add field metadata history failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string AddFieldMetadataHistory {
            get {
                return ResourceManager.GetString("AddFieldMetadataHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve work items failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string ApproveWorkItemsFail {
            get {
                return ResourceManager.GetString("ApproveWorkItemsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate user failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string AuthenticateUserFail {
            get {
                return ResourceManager.GetString("AuthenticateUserFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can&apos;t be authorized to use the system..
        /// </summary>
        internal static string AuthorizedUserFail {
            get {
                return ResourceManager.GetString("AuthorizedUserFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string ChangePasswordFail {
            get {
                return ResourceManager.GetString("ChangePasswordFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete action failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string DeleteActionLogFail {
            get {
                return ResourceManager.GetString("DeleteActionLogFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save ambiguous definition failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string DeleteAmbiguousDefinitionFail {
            get {
                return ResourceManager.GetString("DeleteAmbiguousDefinitionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete bar code  configuration failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string DeleteBarcodeConfigurationFail {
            get {
                return ResourceManager.GetString("DeleteBarcodeConfigurationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete document failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string DeleteDocumentFail {
            get {
                return ResourceManager.GetString("DeleteDocumentFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete document type failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string DeleteDocumentTypeFail {
            get {
                return ResourceManager.GetString("DeleteDocumentTypeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete lookup info failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string DeleteLookupInfoFail {
            get {
                return ResourceManager.GetString("DeleteLookupInfoFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete OCR template failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string DeleteOCRTemplateFail {
            get {
                return ResourceManager.GetString("DeleteOCRTemplateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete page failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string DeletePageFail {
            get {
                return ResourceManager.GetString("DeletePageFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string DeleteUserFail {
            get {
                return ResourceManager.GetString("DeleteUserFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user group failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string DeleteUserGroupFail {
            get {
                return ResourceManager.GetString("DeleteUserGroupFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete work item failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string DeleteWorkItemFail {
            get {
                return ResourceManager.GetString("DeleteWorkItemFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get action logfailed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetActionLogFail {
            get {
                return ResourceManager.GetString("GetActionLogFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ambiguous definition failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetAmbiguousDefinitionFail {
            get {
                return ResourceManager.GetString("GetAmbiguousDefinitionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get annotation permission failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetAnnotationPermissionFail {
            get {
                return ResourceManager.GetString("GetAnnotationPermissionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get audit permission fail. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetAuditPermissionFail {
            get {
                return ResourceManager.GetString("GetAuditPermissionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get barcode configuration failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetBarcodeConfigurationFail {
            get {
                return ResourceManager.GetString("GetBarcodeConfigurationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get capture document failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetCapturedDocumentTypeFail {
            get {
                return ResourceManager.GetString("GetCapturedDocumentTypeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get column failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetColumnFail {
            get {
                return ResourceManager.GetString("GetColumnFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get database names failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetDatabaseNameFail {
            get {
                return ResourceManager.GetString("GetDatabaseNameFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get data column failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetDataColumnNameFail {
            get {
                return ResourceManager.GetString("GetDataColumnNameFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get database schema failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetDBSchemaFail {
            get {
                return ResourceManager.GetString("GetDBSchemaFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get permissions of document type failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetDocTypePermissionFail {
            get {
                return ResourceManager.GetString("GetDocTypePermissionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get document type version failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetDocTypeVersionFail {
            get {
                return ResourceManager.GetString("GetDocTypeVersionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get document failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetDocumentFail {
            get {
                return ResourceManager.GetString("GetDocumentFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get document types failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetDocumentTypeFail {
            get {
                return ResourceManager.GetString("GetDocumentTypeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get document version failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetDocVersionFail {
            get {
                return ResourceManager.GetString("GetDocVersionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get language data failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetLanguageDataFail {
            get {
                return ResourceManager.GetString("GetLanguageDataFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get lookup data failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetLookupDataFail {
            get {
                return ResourceManager.GetString("GetLookupDataFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get parameter failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetLookupDataParameterFail {
            get {
                return ResourceManager.GetString("GetLookupDataParameterFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get lookup data source failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetLookupDatasourceFail {
            get {
                return ResourceManager.GetString("GetLookupDatasourceFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getlookup info failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetLookupInfoFail {
            get {
                return ResourceManager.GetString("GetLookupInfoFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get parameter failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetParameterFail {
            get {
                return ResourceManager.GetString("GetParameterFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get search query failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetSaveQuery {
            get {
                return ResourceManager.GetString("GetSaveQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get search query failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetSearchQuery {
            get {
                return ResourceManager.GetString("GetSearchQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get setting failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetSettingFail {
            get {
                return ResourceManager.GetString("GetSettingFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get user groups failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetUserGroupsFail {
            get {
                return ResourceManager.GetString("GetUserGroupsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get users failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetUsersFail {
            get {
                return ResourceManager.GetString("GetUsersFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get workflow data failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetWorkflowDataFail {
            get {
                return ResourceManager.GetString("GetWorkflowDataFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get workflow document failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetWorkflowDocumentTypeFail {
            get {
                return ResourceManager.GetString("GetWorkflowDocumentTypeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get workflow human step permissions failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetWorkflowHumanStepPermissionsFail {
            get {
                return ResourceManager.GetString("GetWorkflowHumanStepPermissionsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get work item failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetWorkItemFail {
            get {
                return ResourceManager.GetString("GetWorkItemFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert document failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string InsertDocumentFail {
            get {
                return ResourceManager.GetString("InsertDocumentFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert page failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string InsertPageFail {
            get {
                return ResourceManager.GetString("InsertPageFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject work items failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string RejectWorkItemsFail {
            get {
                return ResourceManager.GetString("RejectWorkItemsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password fail. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string ResetPasswordFail {
            get {
                return ResourceManager.GetString("ResetPasswordFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume work items failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string ResumeWorkItemsFail {
            get {
                return ResourceManager.GetString("ResumeWorkItemsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run advance search failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string RunAdvanceSearchFail {
            get {
                return ResourceManager.GetString("RunAdvanceSearchFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run advance search work item failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string RunAdvanceSearchWorkItemFail {
            get {
                return ResourceManager.GetString("RunAdvanceSearchWorkItemFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run global search failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string RunGlobalSearchFail {
            get {
                return ResourceManager.GetString("RunGlobalSearchFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save ambiguous definition failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string SaveAmbiguousDefinitionFail {
            get {
                return ResourceManager.GetString("SaveAmbiguousDefinitionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save annotation permission failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string SaveAnnotationPermissionFail {
            get {
                return ResourceManager.GetString("SaveAnnotationPermissionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save bar code  configuration failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string SaveBarcodeConfigurationFail {
            get {
                return ResourceManager.GetString("SaveBarcodeConfigurationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save permissions of document type failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string SaveDocTypePermissionFail {
            get {
                return ResourceManager.GetString("SaveDocTypePermissionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save document type failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string SaveDocumentTypeFail {
            get {
                return ResourceManager.GetString("SaveDocumentTypeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save language data failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string SaveLanguageDataFail {
            get {
                return ResourceManager.GetString("SaveLanguageDataFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save OCR template failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string SaveOCRTemplateFail {
            get {
                return ResourceManager.GetString("SaveOCRTemplateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save query failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string SaveSearchQuery {
            get {
                return ResourceManager.GetString("SaveSearchQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save user failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string SaveUserFail {
            get {
                return ResourceManager.GetString("SaveUserFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save user group failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string SaveUserGroupFail {
            get {
                return ResourceManager.GetString("SaveUserGroupFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save workflow failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string SaveWorkflowDefinitionFail {
            get {
                return ResourceManager.GetString("SaveWorkflowDefinitionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test connection failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string TestConnectionFail {
            get {
                return ResourceManager.GetString("TestConnectionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Username or Incorrect Password.
        /// </summary>
        internal static string UnknowUser {
            get {
                return ResourceManager.GetString("UnknowUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-lock work items failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string UnLockWorkItemsFail {
            get {
                return ResourceManager.GetString("UnLockWorkItemsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update document failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string UpdateDocumentFail {
            get {
                return ResourceManager.GetString("UpdateDocumentFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write file to server error..
        /// </summary>
        internal static string WriteFileFail {
            get {
                return ResourceManager.GetString("WriteFileFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wirte setting failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string WriteSettingFail {
            get {
                return ResourceManager.GetString("WriteSettingFail", resourceCulture);
            }
        }
    }
}
