//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaptureMVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CaptureResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CaptureResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaptureMVC.Resources.CaptureResources", typeof(CaptureResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password failed!.
        /// </summary>
        public static string Login_PasswordFailed {
            get {
                return ResourceManager.GetString("Login_PasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close all tasks.
        /// </summary>
        public static string MenuCloseAll {
            get {
                return ResourceManager.GetString("MenuCloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close other tasks.
        /// </summary>
        public static string MenuCloseOther {
            get {
                return ResourceManager.GetString("MenuCloseOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string MenuCloseThis {
            get {
                return ResourceManager.GetString("MenuCloseThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete batch?.
        /// </summary>
        public static string MessageConfirmDeleteBatch {
            get {
                return ResourceManager.GetString("MessageConfirmDeleteBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete document?.
        /// </summary>
        public static string MessageConfirmDeleteDoc {
            get {
                return ResourceManager.GetString("MessageConfirmDeleteDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete page?.
        /// </summary>
        public static string MessageConfirmDeletePage {
            get {
                return ResourceManager.GetString("MessageConfirmDeletePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save batch?.
        /// </summary>
        public static string MessageConfirmSave {
            get {
                return ResourceManager.GetString("MessageConfirmSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid position for this page..
        /// </summary>
        public static string MessageInvalidPositionPage {
            get {
                return ResourceManager.GetString("MessageInvalidPositionPage", resourceCulture);
            }
        }
    }
}
