//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaptureMVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CaptureViewerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CaptureViewerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaptureMVC.Resources.CaptureViewerResources", typeof(CaptureViewerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to see detail.
        /// </summary>
        public static string ClickDetailTable {
            get {
                return ResourceManager.GetString("ClickDetailTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to add new row.
        /// </summary>
        public static string ClickNewRow {
            get {
                return ResourceManager.GetString("ClickNewRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment(s).
        /// </summary>
        public static string CommentTitle {
            get {
                return ResourceManager.GetString("CommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create by.
        /// </summary>
        public static string CreateBy {
            get {
                return ResourceManager.GetString("CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create on.
        /// </summary>
        public static string CreateOn {
            get {
                return ResourceManager.GetString("CreateOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto create another batch after submit..
        /// </summary>
        public static string DlgCreate_LblAutoCreateAnother {
            get {
                return ResourceManager.GetString("DlgCreate_LblAutoCreateAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch name.
        /// </summary>
        public static string DlgCreate_LblBatchName {
            get {
                return ResourceManager.GetString("DlgCreate_LblBatchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch type selection.
        /// </summary>
        public static string DlgCreate_LblBatchTypeSelection {
            get {
                return ResourceManager.GetString("DlgCreate_LblBatchTypeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopen this dialog after submit..
        /// </summary>
        public static string DlgCreate_LblReopenDialog {
            get {
                return ResourceManager.GetString("DlgCreate_LblReopenDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create batch information.
        /// </summary>
        public static string DlgCreate_TitleDialog {
            get {
                return ResourceManager.GetString("DlgCreate_TitleDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a photo/video from camera.
        /// </summary>
        public static string LeftBar_BtnCamera {
            get {
                return ResourceManager.GetString("LeftBar_BtnCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create batch.
        /// </summary>
        public static string LeftBar_BtnCreateBatch {
            get {
                return ResourceManager.GetString("LeftBar_BtnCreateBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import document from file system.
        /// </summary>
        public static string LeftBar_BtnImport {
            get {
                return ResourceManager.GetString("LeftBar_BtnImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string LeftBar_BtnNext {
            get {
                return ResourceManager.GetString("LeftBar_BtnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string LeftBar_BtnOptions {
            get {
                return ResourceManager.GetString("LeftBar_BtnOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string LeftBar_BtnPrevious {
            get {
                return ResourceManager.GetString("LeftBar_BtnPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string LeftBar_BtnSave {
            get {
                return ResourceManager.GetString("LeftBar_BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string LeftBar_BtnScan {
            get {
                return ResourceManager.GetString("LeftBar_BtnScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string LeftBar_BtnSubmit {
            get {
                return ResourceManager.GetString("LeftBar_BtnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to docType(s).
        /// </summary>
        public static string LeftBar_CountDocInBatchIndexes {
            get {
                return ResourceManager.GetString("LeftBar_CountDocInBatchIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doc(s).
        /// </summary>
        public static string LeftBar_CountDocInDocIndexes {
            get {
                return ResourceManager.GetString("LeftBar_CountDocInDocIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch indexes.
        /// </summary>
        public static string LeftBar_TabBatchIndexes {
            get {
                return ResourceManager.GetString("LeftBar_TabBatchIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string LeftBar_TabComments {
            get {
                return ResourceManager.GetString("LeftBar_TabComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexes.
        /// </summary>
        public static string LeftBar_TabIndexes {
            get {
                return ResourceManager.GetString("LeftBar_TabIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnails.
        /// </summary>
        public static string LeftBar_TabThumbnails {
            get {
                return ResourceManager.GetString("LeftBar_TabThumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch indexes.
        /// </summary>
        public static string LeftBar_TitleBatchIndexes {
            get {
                return ResourceManager.GetString("LeftBar_TitleBatchIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content indexes.
        /// </summary>
        public static string LeftBar_TitleDocIndexes {
            get {
                return ResourceManager.GetString("LeftBar_TitleDocIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page(s).
        /// </summary>
        public static string LeftBar_TotalPage {
            get {
                return ResourceManager.GetString("LeftBar_TotalPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append.
        /// </summary>
        public static string Menu_Append {
            get {
                return ResourceManager.GetString("Menu_Append", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string Menu_Camera {
            get {
                return ResourceManager.GetString("Menu_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change batch type.
        /// </summary>
        public static string Menu_ChangeBatchType {
            get {
                return ResourceManager.GetString("Menu_ChangeBatchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change content type.
        /// </summary>
        public static string Menu_ChangeDocType {
            get {
                return ResourceManager.GetString("Menu_ChangeDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classify later.
        /// </summary>
        public static string Menu_Classify {
            get {
                return ResourceManager.GetString("Menu_Classify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Menu_Delete {
            get {
                return ResourceManager.GetString("Menu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import file.
        /// </summary>
        public static string Menu_ImportFile {
            get {
                return ResourceManager.GetString("Menu_ImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Menu_Index {
            get {
                return ResourceManager.GetString("Menu_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert after.
        /// </summary>
        public static string Menu_InsertAfter {
            get {
                return ResourceManager.GetString("Menu_InsertAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert before.
        /// </summary>
        public static string Menu_InsertBefore {
            get {
                return ResourceManager.GetString("Menu_InsertBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content language setting.
        /// </summary>
        public static string Menu_LanguageSetting {
            get {
                return ResourceManager.GetString("Menu_LanguageSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New content.
        /// </summary>
        public static string Menu_NewDoc {
            get {
                return ResourceManager.GetString("Menu_NewDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New document from selected page.
        /// </summary>
        public static string Menu_NewDocFromPage {
            get {
                return ResourceManager.GetString("Menu_NewDocFromPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename batch.
        /// </summary>
        public static string Menu_RenameBatch {
            get {
                return ResourceManager.GetString("Menu_RenameBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename content.
        /// </summary>
        public static string Menu_RenameDoc {
            get {
                return ResourceManager.GetString("Menu_RenameDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string Menu_Replace {
            get {
                return ResourceManager.GetString("Menu_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate left.
        /// </summary>
        public static string Menu_RotateLeft {
            get {
                return ResourceManager.GetString("Menu_RotateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate right.
        /// </summary>
        public static string Menu_RotateRight {
            get {
                return ResourceManager.GetString("Menu_RotateRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Menu_Save {
            get {
                return ResourceManager.GetString("Menu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string Menu_Scan {
            get {
                return ResourceManager.GetString("Menu_Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Menu_Submit {
            get {
                return ResourceManager.GetString("Menu_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remains.
        /// </summary>
        public static string RemainsCharater {
            get {
                return ResourceManager.GetString("RemainsCharater", resourceCulture);
            }
        }
    }
}
