//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaptureMVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ControlPanelViewerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlPanelViewerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaptureMVC.Resources.ControlPanelViewerResources", typeof(ControlPanelViewerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add highlight.
        /// </summary>
        public static string TitleAddHighlight {
            get {
                return ResourceManager.GetString("TitleAddHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add redaction.
        /// </summary>
        public static string TitleAddRedaction {
            get {
                return ResourceManager.GetString("TitleAddRedaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add text.
        /// </summary>
        public static string TitleAddText {
            get {
                return ResourceManager.GetString("TitleAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit height.
        /// </summary>
        public static string TitleFitHeight {
            get {
                return ResourceManager.GetString("TitleFitHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to viewer.
        /// </summary>
        public static string TitleFitToViewer {
            get {
                return ResourceManager.GetString("TitleFitToViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit width.
        /// </summary>
        public static string TitleFitWidth {
            get {
                return ResourceManager.GetString("TitleFitWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide all annotations.
        /// </summary>
        public static string TitleHideAnnos {
            get {
                return ResourceManager.GetString("TitleHideAnnos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation down.
        /// </summary>
        public static string TitleNavigationDown {
            get {
                return ResourceManager.GetString("TitleNavigationDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation up.
        /// </summary>
        public static string TitleNavigationUp {
            get {
                return ResourceManager.GetString("TitleNavigationUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan.
        /// </summary>
        public static string TitlePan {
            get {
                return ResourceManager.GetString("TitlePan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string TitlePrint {
            get {
                return ResourceManager.GetString("TitlePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation left.
        /// </summary>
        public static string TitleRotateLeft {
            get {
                return ResourceManager.GetString("TitleRotateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation right.
        /// </summary>
        public static string TitleRotateRight {
            get {
                return ResourceManager.GetString("TitleRotateRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string TitleSave {
            get {
                return ResourceManager.GetString("TitleSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string TitleSelect {
            get {
                return ResourceManager.GetString("TitleSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send mail.
        /// </summary>
        public static string TitleSendMail {
            get {
                return ResourceManager.GetString("TitleSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all annotations.
        /// </summary>
        public static string TitleShowAnnos {
            get {
                return ResourceManager.GetString("TitleShowAnnos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in.
        /// </summary>
        public static string TitleZoomIn {
            get {
                return ResourceManager.GetString("TitleZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        public static string TitleZoomOut {
            get {
                return ResourceManager.GetString("TitleZoomOut", resourceCulture);
            }
        }
    }
}
