//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaptureMVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FieldResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FieldResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaptureMVC.Resources.FieldResources", typeof(FieldResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity name.
        /// </summary>
        public static string Activity_name {
            get {
                return ResourceManager.GetString("Activity_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch name.
        /// </summary>
        public static string Batch_name {
            get {
                return ResourceManager.GetString("Batch_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocking date.
        /// </summary>
        public static string Blocking_date {
            get {
                return ResourceManager.GetString("Blocking_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string Created_by {
            get {
                return ResourceManager.GetString("Created_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created date.
        /// </summary>
        public static string Created_on {
            get {
                return ResourceManager.GetString("Created_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document count.
        /// </summary>
        public static string Doc_count {
            get {
                return ResourceManager.GetString("Doc_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has error.
        /// </summary>
        public static string Has_error {
            get {
                return ResourceManager.GetString("Has_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last access by.
        /// </summary>
        public static string Last_access_by {
            get {
                return ResourceManager.GetString("Last_access_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last access date.
        /// </summary>
        public static string Last_access_date {
            get {
                return ResourceManager.GetString("Last_access_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked by.
        /// </summary>
        public static string Locked_by {
            get {
                return ResourceManager.GetString("Locked_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified by.
        /// </summary>
        public static string Modified_by {
            get {
                return ResourceManager.GetString("Modified_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified date.
        /// </summary>
        public static string Modified_on {
            get {
                return ResourceManager.GetString("Modified_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page count.
        /// </summary>
        public static string Page_count {
            get {
                return ResourceManager.GetString("Page_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
    }
}
