//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecm.CaptureAdmin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateDocTypeViewRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateDocTypeViewRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ecm.CaptureAdmin.CreateDocTypeViewRes", typeof(CreateDocTypeViewRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string btnAdd_Text {
            get {
                return ResourceManager.GetString("btnAdd.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string btnAddField_Text {
            get {
                return ResourceManager.GetString("btnAddField.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancel_Text {
            get {
                return ResourceManager.GetString("btnCancel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        public static string btnConfig_Text {
            get {
                return ResourceManager.GetString("btnConfig.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure OCR template.
        /// </summary>
        public static string btnConfigOCRTemplate_Text {
            get {
                return ResourceManager.GetString("btnConfigOCRTemplate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string btnDelete_Text {
            get {
                return ResourceManager.GetString("btnDelete.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string btnDeleteField_Text {
            get {
                return ResourceManager.GetString("btnDeleteField.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string btnEdit_Text {
            get {
                return ResourceManager.GetString("btnEdit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSave_Text {
            get {
                return ResourceManager.GetString("btnSave.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default value.
        /// </summary>
        public static string gcDefaultValueHeader_Header {
            get {
                return ResourceManager.GetString("gcDefaultValueHeader.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string gcFieldNameHeader_Header {
            get {
                return ResourceManager.GetString("gcFieldNameHeader.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string gcFieldRequiredHeader_Header {
            get {
                return ResourceManager.GetString("gcFieldRequiredHeader.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restricted.
        /// </summary>
        public static string gcFieldRestrictedHeader_Header {
            get {
                return ResourceManager.GetString("gcFieldRestrictedHeader.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string gcFieldTypeHeader_Header {
            get {
                return ResourceManager.GetString("gcFieldTypeHeader.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has lookup.
        /// </summary>
        public static string gcHasLookupHeader_Header {
            get {
                return ResourceManager.GetString("gcHasLookupHeader.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR template.
        /// </summary>
        public static string gcHasOCRHeader_Header {
            get {
                return ResourceManager.GetString("gcHasOCRHeader.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup.
        /// </summary>
        public static string gcLookupHeader_Header {
            get {
                return ResourceManager.GetString("gcLookupHeader.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length.
        /// </summary>
        public static string gcMaxLenghtHeader_Header {
            get {
                return ResourceManager.GetString("gcMaxLenghtHeader.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string gcNameHeader_Header {
            get {
                return ResourceManager.GetString("gcNameHeader.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        public static string lblBarcode_Text {
            get {
                return ResourceManager.GetString("lblBarcode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR template.
        /// </summary>
        public static string lblOCRTemplate_Text {
            get {
                return ResourceManager.GetString("lblOCRTemplate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply for Outlook import.
        /// </summary>
        public static string tbApplyForImport_Text {
            get {
                return ResourceManager.GetString("tbApplyForImport.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This content is being run on the workflow so CANNOT modify..
        /// </summary>
        public static string tbCanNotModify_Line1 {
            get {
                return ResourceManager.GetString("tbCanNotModify_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to modify, please delete or release the batch to archive first..
        /// </summary>
        public static string tbCanNotModify_Line2 {
            get {
                return ResourceManager.GetString("tbCanNotModify_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode configuration for.
        /// </summary>
        public static string tbConfigBarcodeTitle_Text {
            get {
                return ResourceManager.GetString("tbConfigBarcodeTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon (Support PNG format with size 20X20).
        /// </summary>
        public static string tbIcon_Text {
            get {
                return ResourceManager.GetString("tbIcon.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string tbLanguage_Text {
            get {
                return ResourceManager.GetString("tbLanguage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template file.
        /// </summary>
        public static string tbOCRTemplateFile_Text {
            get {
                return ResourceManager.GetString("tbOCRTemplateFile.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content type properties.
        /// </summary>
        public static string tbType_Text {
            get {
                return ResourceManager.GetString("tbType.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content type name.
        /// </summary>
        public static string tbTypeName_Text {
            get {
                return ResourceManager.GetString("tbTypeName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content types.
        /// </summary>
        public static string tbViewText_Text {
            get {
                return ResourceManager.GetString("tbViewText.Text", resourceCulture);
            }
        }
    }
}
