//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecm.CaptureCore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ecm.CaptureCore.Properties.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch has been completed..
        /// </summary>
        internal static string BatchCompleted {
            get {
                return ResourceManager.GetString("BatchCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch is in processing..
        /// </summary>
        internal static string BatchInProcess {
            get {
                return ResourceManager.GetString("BatchInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch has benn locked by user {0}..
        /// </summary>
        internal static string BatchLocked {
            get {
                return ResourceManager.GetString("BatchLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch not found..
        /// </summary>
        internal static string BatchNotExist {
            get {
                return ResourceManager.GetString("BatchNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document not found..
        /// </summary>
        internal static string DocumentNotExist {
            get {
                return ResourceManager.GetString("DocumentNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List batch field value is in more than 1 batch..
        /// </summary>
        internal static string HaveMoreBatch {
            get {
                return ResourceManager.GetString("HaveMoreBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid comments of batch..
        /// </summary>
        internal static string InvalidBatchComment {
            get {
                return ResourceManager.GetString("InvalidBatchComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch has invalid field value..
        /// </summary>
        internal static string InvalidBatchField {
            get {
                return ResourceManager.GetString("InvalidBatchField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document has invalid field value..
        /// </summary>
        internal static string InvalidDocField {
            get {
                return ResourceManager.GetString("InvalidDocField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document has invalid data..
        /// </summary>
        internal static string InvalidDocumentData {
            get {
                return ResourceManager.GetString("InvalidDocumentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field value do not match with validation pattern or condition..
        /// </summary>
        internal static string InvalidEnterData {
            get {
                return ResourceManager.GetString("InvalidEnterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page has invalid data..
        /// </summary>
        internal static string InvalidPageData {
            get {
                return ResourceManager.GetString("InvalidPageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has not permission to access doument type {1}..
        /// </summary>
        internal static string NoAccessPermission {
            get {
                return ResourceManager.GetString("NoAccessPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has not permission to delete item(s) on batch {1}..
        /// </summary>
        internal static string NoDeletePermission {
            get {
                return ResourceManager.GetString("NoDeletePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has not permission to unlocked work item(s) {1}..
        /// </summary>
        internal static string NoLockPermission {
            get {
                return ResourceManager.GetString("NoLockPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has not permission to modify document(s) on batch {1}..
        /// </summary>
        internal static string NoModifyDocumentPermission {
            get {
                return ResourceManager.GetString("NoModifyDocumentPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has not permission to modify field value(s) on batch {1}..
        /// </summary>
        internal static string NoModifyIndexPermission {
            get {
                return ResourceManager.GetString("NoModifyIndexPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has not permission on batch {1}..
        /// </summary>
        internal static string NoPermission {
            get {
                return ResourceManager.GetString("NoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has not permission to reject batch {1}..
        /// </summary>
        internal static string NoRejectPermission {
            get {
                return ResourceManager.GetString("NoRejectPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has not permission to release loose page(s) on batch {1}..
        /// </summary>
        internal static string NoReleaseLoosePagePermission {
            get {
                return ResourceManager.GetString("NoReleaseLoosePagePermission", resourceCulture);
            }
        }
    }
}
