//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecm.CaptureService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ecm.CaptureService.Properties.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve work items failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string ApproveWorkItemsFail {
            get {
                return ResourceManager.GetString("ApproveWorkItemsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate user failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string AuthenticateUserFail {
            get {
                return ResourceManager.GetString("AuthenticateUserFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can&apos;t be authorized to use the system..
        /// </summary>
        internal static string AuthorizedUserFail {
            get {
                return ResourceManager.GetString("AuthorizedUserFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check can edit Batch type&apos;s field failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string CanEditBatchTypeFieldFail {
            get {
                return ResourceManager.GetString("CanEditBatchTypeFieldFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check can edit Document type&apos;s field failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string CanEditDocTypeFieldFail {
            get {
                return ResourceManager.GetString("CanEditDocTypeFieldFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string ChangePasswordFail {
            get {
                return ResourceManager.GetString("ChangePasswordFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate work item(s) failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string DelegateWorkItemFail {
            get {
                return ResourceManager.GetString("DelegateWorkItemFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete action logfailed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string DeleteActionLogFail {
            get {
                return ResourceManager.GetString("DeleteActionLogFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save ambiguous definition failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string DeleteAmbiguousDefinitionFail {
            get {
                return ResourceManager.GetString("DeleteAmbiguousDefinitionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete bar code  configuration failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string DeleteBarcodeConfigurationFail {
            get {
                return ResourceManager.GetString("DeleteBarcodeConfigurationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete batch type failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string DeleteBatchTypeFail {
            get {
                return ResourceManager.GetString("DeleteBatchTypeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete OCR template failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string DeleteOCRTemplateFail {
            get {
                return ResourceManager.GetString("DeleteOCRTemplateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string DeleteUserFail {
            get {
                return ResourceManager.GetString("DeleteUserFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user group failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string DeleteUserGroupFail {
            get {
                return ResourceManager.GetString("DeleteUserGroupFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete work item failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string DeleteWorkItemFail {
            get {
                return ResourceManager.GetString("DeleteWorkItemFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get action logfailed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetActionLogFail {
            get {
                return ResourceManager.GetString("GetActionLogFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ambiguous definition failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetAmbiguousDefinitionFail {
            get {
                return ResourceManager.GetString("GetAmbiguousDefinitionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get barcode configuration failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetBarcodeConfigurationFail {
            get {
                return ResourceManager.GetString("GetBarcodeConfigurationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get work item failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetBatchFail {
            get {
                return ResourceManager.GetString("GetBatchFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get batch types failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetBatchTypeFail {
            get {
                return ResourceManager.GetString("GetBatchTypeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get permissions of batch type failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetBatchTypePermissionFail {
            get {
                return ResourceManager.GetString("GetBatchTypePermissionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get lookup column failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetColumnFail {
            get {
                return ResourceManager.GetString("GetColumnFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get custom activity setting failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetCustonActivitySettingFail {
            get {
                return ResourceManager.GetString("GetCustonActivitySettingFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get database names failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetDatabaseNameFail {
            get {
                return ResourceManager.GetString("GetDatabaseNameFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get data column failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetDataColumnNameFail {
            get {
                return ResourceManager.GetString("GetDataColumnNameFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get database schema fail. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetDBSchemaFail {
            get {
                return ResourceManager.GetString("GetDBSchemaFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get document type failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetDocTypeFail {
            get {
                return ResourceManager.GetString("GetDocTypeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get language data failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetLanguageDataFail {
            get {
                return ResourceManager.GetString("GetLanguageDataFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get lookup data failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetLookupDataFail {
            get {
                return ResourceManager.GetString("GetLookupDataFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get parameter failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetLookupDataParameterFail {
            get {
                return ResourceManager.GetString("GetLookupDataParameterFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get lookup data source failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetLookupDatasourceFail {
            get {
                return ResourceManager.GetString("GetLookupDatasourceFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get lookup stored parameter failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetParameterFail {
            get {
                return ResourceManager.GetString("GetParameterFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get search query failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetSaveQuery {
            get {
                return ResourceManager.GetString("GetSaveQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get search query failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetSearchQuery {
            get {
                return ResourceManager.GetString("GetSearchQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get setting failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetSettingFail {
            get {
                return ResourceManager.GetString("GetSettingFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get user groups failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetUserGroupsFail {
            get {
                return ResourceManager.GetString("GetUserGroupsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get users failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetUsersFail {
            get {
                return ResourceManager.GetString("GetUsersFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get workflow data failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetWorkflowDataFail {
            get {
                return ResourceManager.GetString("GetWorkflowDataFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get workflow human step permissions failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetWorkflowHumanStepPermissionsFail {
            get {
                return ResourceManager.GetString("GetWorkflowHumanStepPermissionsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get work item failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string GetWorkItemFail {
            get {
                return ResourceManager.GetString("GetWorkItemFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert work item failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string InsertWorkItemFail {
            get {
                return ResourceManager.GetString("InsertWorkItemFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject work items failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string RejectWorkItemsFail {
            get {
                return ResourceManager.GetString("RejectWorkItemsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string ResetPasswordFail {
            get {
                return ResourceManager.GetString("ResetPasswordFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume work items failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string ResumeWorkItemsFail {
            get {
                return ResourceManager.GetString("ResumeWorkItemsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run advance search failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string RunAdvanceSearchWorkItemFail {
            get {
                return ResourceManager.GetString("RunAdvanceSearchWorkItemFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save ambiguous definition failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string SaveAmbiguousDefinitionFail {
            get {
                return ResourceManager.GetString("SaveAmbiguousDefinitionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save bar code  configuration failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string SaveBarcodeConfigurationFail {
            get {
                return ResourceManager.GetString("SaveBarcodeConfigurationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save batch type failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string SaveBatchTypeFail {
            get {
                return ResourceManager.GetString("SaveBatchTypeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save permissions of batch type failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string SaveBatchTypePermissionFail {
            get {
                return ResourceManager.GetString("SaveBatchTypePermissionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save OCR template failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string SaveOCRTemplateFail {
            get {
                return ResourceManager.GetString("SaveOCRTemplateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save query failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string SaveSearchQuery {
            get {
                return ResourceManager.GetString("SaveSearchQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save user failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string SaveUserFail {
            get {
                return ResourceManager.GetString("SaveUserFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save user group failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string SaveUserGroupFail {
            get {
                return ResourceManager.GetString("SaveUserGroupFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save workflow failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string SaveWorkflowDefinitionFail {
            get {
                return ResourceManager.GetString("SaveWorkflowDefinitionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test connection failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string TestConnectionFail {
            get {
                return ResourceManager.GetString("TestConnectionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Username or Incorrect Password.
        /// </summary>
        internal static string UnknowUser {
            get {
                return ResourceManager.GetString("UnknowUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-lock work items failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string UnLockWorkItemsFail {
            get {
                return ResourceManager.GetString("UnLockWorkItemsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update lookup info fail. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string UpdateLookupInfoFail {
            get {
                return ResourceManager.GetString("UpdateLookupInfoFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update work item failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string UpdateWorkItemFail {
            get {
                return ResourceManager.GetString("UpdateWorkItemFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save setting failed. Please contact your system administrator or review the log file..
        /// </summary>
        internal static string WriteSettingFail {
            get {
                return ResourceManager.GetString("WriteSettingFail", resourceCulture);
            }
        }
    }
}
