//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecm.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ecm.Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9999-12-31.
        /// </summary>
        internal static string MaxDate {
            get {
                return ResourceManager.GetString("MaxDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1753-1-1.
        /// </summary>
        internal static string MinDate {
            get {
                return ResourceManager.GetString("MinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content type is blank..
        /// </summary>
        internal static string uiContentTypeEmpty {
            get {
                return ResourceManager.GetString("uiContentTypeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content type name is already existed..
        /// </summary>
        internal static string uiContentTypeNameExisted {
            get {
                return ResourceManager.GetString("uiContentTypeNameExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is invalid format..
        /// </summary>
        internal static string uiEmailInvalid {
            get {
                return ResourceManager.GetString("uiEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field name is already existed..
        /// </summary>
        internal static string uiFieldNameExisted {
            get {
                return ResourceManager.GetString("uiFieldNameExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid date is between 1/1/1753 and 12/31/9999..
        /// </summary>
        internal static string uiInvalidDateMessage {
            get {
                return ResourceManager.GetString("uiInvalidDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a required field..
        /// </summary>
        internal static string uiRequiredValueMessage {
            get {
                return ResourceManager.GetString("uiRequiredValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User group is already existed..
        /// </summary>
        internal static string uiUserGroupExisted {
            get {
                return ResourceManager.GetString("uiUserGroupExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User group name is blank..
        /// </summary>
        internal static string uiUserGroupNameEmpty {
            get {
                return ResourceManager.GetString("uiUserGroupNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is blank..
        /// </summary>
        internal static string uiUserNameEmpty {
            get {
                return ResourceManager.GetString("uiUserNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already existed..
        /// </summary>
        internal static string uiUsernameExisted {
            get {
                return ResourceManager.GetString("uiUsernameExisted", resourceCulture);
            }
        }
    }
}
